formatter: markdown table

output:
  file: README.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

sections:
  show:
    - requirements
    - providers
    - resources
    - inputs
    - outputs

sort:
  enabled: true
  by: name

settings:
  anchor: true
  default: true
  escape: true
  hide-empty: true
  html: true
  indent: 2
  read-comments: true
  required: true
  sensitive: true
  type: true
